### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by aidenybai** [yigalirani/million_try2#1]
Try using [keys](https://million.js.org/functions/m#optimization-via-keys) and `VFlags.ONLY_KEYED_CHILDREN` or [deltas](https://million.js.org/functions/m#deltas) to improve performance. The base algorithm is just straight virtual dom which can be non-performant

**Comment by yigalirani** [comment]
thank you so much for looking at this! i did make the suggested change, but now the display is not updating at all

**Comment by aidenybai** [comment]
Deltas and keys are usually exclusive to each other, so you should either use just keys or just deltas

**Comment by yigalirani** [comment]
i only added keys. i think. look at the code change

**Comment by aidenybai** [comment]
Ah I see, my mistake. 

All your keys should be the same, so something like the `count` could work as a key. Additionally, the root should not have a key, because it has no parent to specify that it has `ONLY_KEYED_CHILDREN`. There is also no need to specify that for the actual children themselves.
